# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: ""
subtitle: ""
author:  ""
header:
 title: ""
 subtitle: ""
footer:
 name: "Hello World! 👋'"
 bio: ""
social_urls:
  instagram: ""
  twitter: ""
